spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zti
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

security:
  user:
    password: admin1